<?php
echo $block->getLayout()

->createBlock('Magento\Cms\Block\Block')

->setBlockId('home-page-carosel')

->toHtml();

?>


<script>
	require([
		'jquery',
		'owlCarousel'
		], function ($) {
			$(document).ready(function() {
				var owl = $('.home-page-owl-carousel');
				owl.owlCarousel({
					items: 1,
					loop: true,
					autoplay: false,
					autoplayTimeout: 1000,
					autoplayHoverPause: true
				});
				$('.play').on('click', function() {
					owl.trigger('play.owl.autoplay', [1000])
				})
				$('.stop').on('click', function() {
					owl.trigger('stop.owl.autoplay')
				})
			});
		});
	</script>