<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php if ($block->isEnabledViewSwitcher()) : ?>
    <div class="modes">
        <span class="view-product-catalog-modes">
            <?php $_modes = $block->getModes(); ?>
            <?php if ($_modes && count($_modes) > 1) : ?>
                <strong class="modes-label" id="modes-label"><?= $block->escapeHtml(__('View as')) ?></strong>
                <?php foreach ($block->getModes() as $_code => $_label) : ?>
                    <?php if ($block->isModeActive($_code)) : ?>
                        <strong title="<?= $block->escapeHtmlAttr($_label) ?>" class="modes-mode active mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>" data-value="<?= $block->escapeHtmlAttr(strtolower($_code)) ?>">
                            <span><?= $block->escapeHtml($_label) ?></span>
                        </strong>
                    <?php else : ?>
                        <a class="modes-mode mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>" title="<?= $block->escapeHtmlAttr($_label) ?>" href="#" data-role="mode-switcher" data-value="<?= $block->escapeHtmlAttr(strtolower($_code)) ?>" id="mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>" aria-labelledby="modes-label mode-<?= $block->escapeHtmlAttr(strtolower($_code)) ?>">
                            <span><?= $block->escapeHtml($_label) ?></span>
                        </a>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>
        </span>
        <span class="limit-product-catalog-modes">
            <select id="limiter" data-role="limiter" class="limiter-options1">
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit) : ?>
                    <option value="<?= $block->escapeHtmlAttr($_key) ?>" <?php if ($block->isLimitCurrent($_key)) : ?> selected="selected" <?php endif ?>>View
                        <?= $block->escapeHtml($_limit) ?> products
                    </option>
                <?php endforeach; ?>
            </select>
        </span>
    </div>
<?php endif; ?>