<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtmlAttr(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()) :?>
                <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                 title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
                 tabindex="-1"
                 class="product-item-photo">
                 <?php else :?>
                    <span class="product-item-photo">
                    <?php endif;?>
                    <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                    <?php if ($block->hasProductUrl()) :?>
                    </a>
                    <?php else :?>
                    </span>
                <?php endif; ?>
                <div class="product-item-details">
                    <strong class="product-item-name">
                        <?php if ($block->hasProductUrl()) :?>
                            <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                            <?php else :?>
                                <?= $block->escapeHtml($block->getProductName()) ?>
                            <?php endif; ?>
                        </strong>


                        <div class="product-item-details-options">

                            <?php if ($_options = $block->getOptionList()) :?>
                                <dl class="item-options">
                                    <?php foreach ($_options as $_option) :?>
                                        <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                                        <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                                        <dd>
                                            <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                                <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                                <?php else :?>
                                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                                <?php endif; ?>
                                                <?= $block->escapeHtml(__(", ")) ?>
                                            </dd>
                                        <?php endforeach; ?>
                                    </dl>
                                <?php endif;?>
                                <?php if ($messages = $block->getMessages()) :?>
                                    <?php foreach ($messages as $message) :?>
                                        <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                                            <div><?= $block->escapeHtml($message['text']) ?></div>
                                        </div>
                                    <?php endforeach; ?>
                                <?php endif; ?>
                                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                                <?php if ($addInfoBlock) :?>
                                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                                <?php endif;?>


                                <?php if ($canApplyMsrp) :?>
                                    <span class="pricing msrp">
                                        <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                                        <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                                        <a href="#" class="action help map"
                                        id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                                        data-mage-init='{"addToCart":{
                                        "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                        "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                        "showAddToCart": false
                                    }
                                }'
                                >
                                <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                            </a>
                        </span>

                        <?php else :?>
                            <span class="price">
                            <?php 
                            if($product->getPrice() > 0 && $product->getTypeId() !== 'configurable'){
                                $UnitOldPriceHtml = $block->convertPrice($product->getPriceInfo()->getPrice('regular_price')->getAmount()->getValue(), true);
                                if ($UnitOldPriceHtml != $block->getUnitPriceHtml($_item)) {
                                    echo "<span>".$block->escapeHtml(__("Was"))."&nbsp</span>".$UnitOldPriceHtml. $block->escapeHtml(__(", "));
                                }
                            };
                            ?>
                            </span>
                            <span class="price-ex-tax">
                            <?php echo "<span>".$block->escapeHtml(__("Now"))."&nbsp</span>".$block->getUnitPriceHtml($_item); ?>
                            </span>
                        <?php endif; ?>
                            

                    </div>

                    <div class="product-code-action">
                        <div class="product-code-action__code">
                            <?= $block->escapeHtml(__("Product code: ")), $block->escapeHtmlAttr($_item->getSku()) ?>
                        </div>
                        <div class="product-code-action__action">
                         <?= /* @noEscape */ $block->getActions($_item) ?>
                     </div>           
                 </div>


             </div>
         </td>

         <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
            <div class="field qty">
                <div class="control qty">
                    <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                        <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                        <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                        name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                        data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                        value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                        type="number"
                        size="4"
                        step="any"
                        title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                        class="input-text qty"
                        data-validate="{required:true,'validate-greater-than-zero':true}"
                        data-role="cart-item-qty"/>
                    </label>
                </div>


                <div class="cart main actions">
                    <?php if ($block->getContinueShoppingUrl()) :?>
                        <a class="action continue"
                        href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
                        title="<?= $block->escapeHtmlAttr(__('Continue Shopping')) ?>">
                        <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
                    </a>
                <?php endif; ?>
            <button type="submit"
            name="update_cart_action"
            data-cart-item-update=""
            value="update_qty"
            title="<?= $block->escapeHtmlAttr(__('Update')) ?>"
            class="action update">
            <span><?= $block->escapeHtml(__('Update')) ?></span>
        </button>
        <input type="hidden" value="" data-cart-item-update=""/>
    </div>
</div>
</td>

<td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
    <?php if ($canApplyMsrp) :?>
        <span class="cart msrp subtotal">--</span>
        <?php else :?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
</tr>
</tbody>

